import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { testDatabaseConnection } from "./actions";

export default async function RootLayout({ children }) {
  const isConnected = await testDatabaseConnection();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        <footer>
          {isConnected ? (
            <h2 className="text-lg text-green-500">
              You are connected to MongoDB!
            </h2>
          ) : (
            <h2 className="text-lg text-red-500">
              You are NOT connected to MongoDB. Check the <code>README.md</code>{" "}
              for instructions.
            </h2>
          )}
        </footer>
      </body>
    </html>
  );
}
